// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messagingpb/kchief.proto

package messagingpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	LibraryVersion       uint32   `protobuf:"varint,1,opt,name=library_version,json=libraryVersion,proto3" json:"library_version,omitempty"`
	Compressed           bool     `protobuf:"varint,3,opt,name=compressed,proto3" json:"compressed,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9f1e0e570356b8, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetLibraryVersion() uint32 {
	if m != nil {
		return m.LibraryVersion
	}
	return 0
}

func (m *Message) GetCompressed() bool {
	if m != nil {
		return m.Compressed
	}
	return false
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DataPoint struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value                []float64            `protobuf:"fixed64,2,rep,packed,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DataPoint) Reset()         { *m = DataPoint{} }
func (m *DataPoint) String() string { return proto.CompactTextString(m) }
func (*DataPoint) ProtoMessage()    {}
func (*DataPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9f1e0e570356b8, []int{1}
}

func (m *DataPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataPoint.Unmarshal(m, b)
}
func (m *DataPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataPoint.Marshal(b, m, deterministic)
}
func (m *DataPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataPoint.Merge(m, src)
}
func (m *DataPoint) XXX_Size() int {
	return xxx_messageInfo_DataPoint.Size(m)
}
func (m *DataPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_DataPoint.DiscardUnknown(m)
}

var xxx_messageInfo_DataPoint proto.InternalMessageInfo

func (m *DataPoint) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DataPoint) GetValue() []float64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type TagDataPoints struct {
	Tag                  string       `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Datapoints           []*DataPoint `protobuf:"bytes,2,rep,name=datapoints,proto3" json:"datapoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TagDataPoints) Reset()         { *m = TagDataPoints{} }
func (m *TagDataPoints) String() string { return proto.CompactTextString(m) }
func (*TagDataPoints) ProtoMessage()    {}
func (*TagDataPoints) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9f1e0e570356b8, []int{2}
}

func (m *TagDataPoints) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagDataPoints.Unmarshal(m, b)
}
func (m *TagDataPoints) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagDataPoints.Marshal(b, m, deterministic)
}
func (m *TagDataPoints) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagDataPoints.Merge(m, src)
}
func (m *TagDataPoints) XXX_Size() int {
	return xxx_messageInfo_TagDataPoints.Size(m)
}
func (m *TagDataPoints) XXX_DiscardUnknown() {
	xxx_messageInfo_TagDataPoints.DiscardUnknown(m)
}

var xxx_messageInfo_TagDataPoints proto.InternalMessageInfo

func (m *TagDataPoints) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TagDataPoints) GetDatapoints() []*DataPoint {
	if m != nil {
		return m.Datapoints
	}
	return nil
}

type Payload struct {
	Tagdatapoints        []*TagDataPoints `protobuf:"bytes,3,rep,name=tagdatapoints,proto3" json:"tagdatapoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9f1e0e570356b8, []int{3}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetTagdatapoints() []*TagDataPoints {
	if m != nil {
		return m.Tagdatapoints
	}
	return nil
}

type Payloads struct {
	Payloads             []*Payload `protobuf:"bytes,1,rep,name=payloads,proto3" json:"payloads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Payloads) Reset()         { *m = Payloads{} }
func (m *Payloads) String() string { return proto.CompactTextString(m) }
func (*Payloads) ProtoMessage()    {}
func (*Payloads) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e9f1e0e570356b8, []int{4}
}

func (m *Payloads) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payloads.Unmarshal(m, b)
}
func (m *Payloads) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payloads.Marshal(b, m, deterministic)
}
func (m *Payloads) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payloads.Merge(m, src)
}
func (m *Payloads) XXX_Size() int {
	return xxx_messageInfo_Payloads.Size(m)
}
func (m *Payloads) XXX_DiscardUnknown() {
	xxx_messageInfo_Payloads.DiscardUnknown(m)
}

var xxx_messageInfo_Payloads proto.InternalMessageInfo

func (m *Payloads) GetPayloads() []*Payload {
	if m != nil {
		return m.Payloads
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "messagingpb.Message")
	proto.RegisterType((*DataPoint)(nil), "messagingpb.DataPoint")
	proto.RegisterType((*TagDataPoints)(nil), "messagingpb.TagDataPoints")
	proto.RegisterType((*Payload)(nil), "messagingpb.Payload")
	proto.RegisterType((*Payloads)(nil), "messagingpb.Payloads")
}

func init() { proto.RegisterFile("messagingpb/kchief.proto", fileDescriptor_3e9f1e0e570356b8) }

var fileDescriptor_3e9f1e0e570356b8 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0xa9, 0x9d, 0x6e, 0x7b, 0x73, 0x2a, 0x61, 0x48, 0xd8, 0x41, 0x4b, 0x2f, 0xf6, 0x94,
	0xc9, 0x04, 0xf1, 0xe0, 0xc1, 0x83, 0x37, 0x11, 0x46, 0x18, 0x82, 0x78, 0x90, 0xd7, 0x2d, 0x8b,
	0xc1, 0xb6, 0x09, 0x4d, 0x36, 0xd8, 0x7f, 0x2f, 0x4b, 0xbb, 0xda, 0xde, 0x5e, 0xde, 0xfb, 0xde,
	0x97, 0x1f, 0x0f, 0x68, 0x2e, 0xac, 0x45, 0xa9, 0x0a, 0x69, 0xd2, 0xd9, 0xef, 0xea, 0x47, 0x89,
	0x0d, 0x33, 0xa5, 0x76, 0x9a, 0x8c, 0x5a, 0x93, 0xe9, 0xad, 0xd4, 0x5a, 0x66, 0x62, 0xe6, 0x47,
	0xe9, 0x76, 0x33, 0x73, 0x2a, 0x17, 0xd6, 0x61, 0x6e, 0x2a, 0x3a, 0xde, 0x40, 0xff, 0xdd, 0xf3,
	0x82, 0xdc, 0xc1, 0x65, 0xa6, 0xd2, 0x12, 0xcb, 0xfd, 0xf7, 0x4e, 0x94, 0x56, 0xe9, 0x82, 0x06,
	0x51, 0x90, 0x8c, 0xf9, 0x45, 0xdd, 0xfe, 0xa8, 0xba, 0xe4, 0x06, 0x60, 0xa5, 0x73, 0x53, 0x0a,
	0x6b, 0xc5, 0x9a, 0x86, 0x51, 0x90, 0x0c, 0x78, 0xab, 0x43, 0x08, 0xf4, 0xd6, 0xe8, 0x90, 0xf6,
	0xa2, 0x20, 0x39, 0xe7, 0xbe, 0x8e, 0xbf, 0x60, 0xf8, 0x8a, 0x0e, 0x17, 0x5a, 0x15, 0x8e, 0x3c,
	0xc1, 0xb0, 0xc9, 0xe1, 0xff, 0x18, 0xcd, 0xa7, 0xac, 0x4a, 0xca, 0x8e, 0x49, 0xd9, 0xf2, 0x48,
	0xf0, 0x7f, 0x98, 0x4c, 0xe0, 0x74, 0x87, 0xd9, 0x56, 0xd0, 0x93, 0x28, 0x4c, 0x02, 0x5e, 0x3d,
	0xe2, 0x4f, 0x18, 0x2f, 0x51, 0x36, 0x7e, 0x4b, 0xae, 0x20, 0x74, 0x28, 0xbd, 0x7a, 0xc8, 0x0f,
	0x25, 0x79, 0x04, 0x38, 0xe4, 0x30, 0x7e, 0xee, 0xb7, 0x47, 0xf3, 0x6b, 0xd6, 0x3a, 0x15, 0x6b,
	0xd6, 0x79, 0x8b, 0x8c, 0xdf, 0xa0, 0xbf, 0xc0, 0x7d, 0xa6, 0x71, 0x4d, 0x5e, 0x60, 0xec, 0x50,
	0xb6, 0x2c, 0xa1, 0xb7, 0x4c, 0x3b, 0x96, 0x4e, 0x0e, 0xde, 0x5d, 0x88, 0x9f, 0x61, 0x50, 0xcb,
	0x2c, 0xb9, 0x87, 0x81, 0xa9, 0x6b, 0x1a, 0x78, 0xd1, 0xa4, 0x23, 0xaa, 0x41, 0xde, 0x50, 0xe9,
	0x99, 0x3f, 0xcd, 0xc3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x27, 0xc3, 0xa3, 0x24, 0xfb, 0x01,
	0x00, 0x00,
}
